### PR TITLE
FEAT: Add Frontend function in the inbox.js

### PR DESCRIPTION
**Pull request by qit2**
### Description of Changes:
- Install all the features on the inbox page except the delete function

### Type of Changes:

- [ ] Documentation (Add Documentation to Existing Code)
- [ ] Bug Fix (Non-Breaking Changes Which Fixes an Issue)
- [x] New Feature (Non-Breaking Changes Which Adds Functionality)
- [ ] Improvement (Non-Breaking Changes Which Improves the Structures, Performance, etc...)
- [ ] **Breaking Change** (Breaking Changes that Would Cause Existing Functionality to NOT Work as Expected)

### To-Do or Other Concerns:

- (NONE)

### CODE REVIEW

**Comment by xiaoshaoyc** [comment]
configured a demo server for dev
https://ec-dev.sycnb.site
Please use **one-time PIN** and **RPI email** for account authorization.

**Comment by xiaoshaoyc** [comment]
> configured a demo server for dev https://ec-dev.sycnb.site Please use **one-time PIN** and **RPI email** for account authorization.

GitHub OAuth login should also work now.

**Review by wangz44 — DISMISSED** [review]

**Comment by Rexezuge** [comment]
Please comment what you did, include screenshots if you are change the user interface.

**Review by xiaoshaoyc — DISMISSED** [review]

**Review by Rexezuge — DISMISSED** [review]

**Review by xiaokeai55 — DISMISSED** [review]

**Review by Reddy017 — APPROVED** [review]
Good

**Review by xiaoshaoyc — APPROVED** [review]

**Pull request merged**
