### PR TITLE
FEAT: Create SendEmailService

### PR DESCRIPTION
**Pull request by xiaoshaoyc**
### Description of Changes:

- Add a service that can send emails
- Implement SMTP for the service

### Type of Changes:

- [ ] Documentation (Add Documentation to Existing Code)
- [ ] Bug Fix (Non-Breaking Changes Which Fixes an Issue)
- [x] New Feature (Non-Breaking Changes Which Adds Functionality)
- [ ] Improvement (Non-Breaking Changes Which Improves the Structures, Performance, etc...)
- [ ] **Breaking Change** (Breaking Changes that Would Cause Existing Functionality to NOT Work as Expected)

### To-Do or Other Concerns:

- TODO: document
- TODO: unit test

### CODE REVIEW

**Review by XiaoyuYang18 — DISMISSED** [review]
good good

**Review by qit2 — COMMENTED** [review]
Looks good

**Review by qit2 — DISMISSED** [review]
LGTM

**Review by ZHIHANCHEN03 — DISMISSED** [review]
Nice work

**Review by wangz44 — DISMISSED** [review]

**Review by xiaokeai55 — DISMISSED** [review]

**Comment by xiaokeai55** [comment]
nice

**Review by ZHIHANCHEN03 — APPROVED** [review]
Great coding

**Review by Viyerelu23333 — APPROVED** [review]

**Pull request merged**
