### PR TITLE
FEAT: new feature Sent and header adjust

### PR DESCRIPTION
**Pull request by wangz44**
new feature Sent
header adjust

### Description of Changes:

- new feature Sent header adjust

### Type of Changes:

- [ ] Documentation (Add Documentation to Existing Code)
- [ ] Bug Fix (Non-Breaking Changes Which Fixes an Issue)
- [x] New Feature (Non-Breaking Changes Which Adds Functionality)
- [ ] Improvement (Non-Breaking Changes Which Improves the Structures, Performance, etc...)
- [ ] **Breaking Change** (Breaking Changes that Would Cause Existing Functionality to NOT Work as Expected)

### To-Do or Other Concerns:

- (NONE)

### CODE REVIEW

**Review by xiaoshaoyc — CHANGES_REQUESTED** [review]
The diff tool is not functioning. I suggest using `git` to upload files.

**Comment by xiaoshaoyc** [comment]
> The diff tool is not functioning. I suggest using `git` to upload files.

Actually, it is working. (LOL) Please change the line break to `LF`.

**Review by ZHIHANCHEN03 — DISMISSED** [review]
Works for me

**Review by xiaokeai55 — DISMISSED** [review]

**Review by xiaoshaoyc — APPROVED** [review]

**Review by qit2 — APPROVED** [review]
Good

**Review by Rexezuge — APPROVED** [review]
Looks good, please resolve all the conflicts before merging.

**Comment by Rexezuge** [comment]
CLOSED: Semester is ended

**Pull request closed without merging**
