### PR TITLE
DOCS: Create APIs.md

### PR DESCRIPTION
**Pull request by ZHIHANCHEN03**
### Description of Changes:

Create APIs.md for designing the restful APIs protocol for the backend

### Type of Changes:

- [x] Documentation (Add Documentation to Existing Code)
- [ ] Bug Fix (Non-Breaking Changes Which Fixes an Issue)
- [ ] New Feature (Non-Breaking Changes Which Adds Functionality)
- [ ] Improvement (Non-Breaking Changes Which Improves the Structures, Performance, etc...)
- [ ] **Breaking Change** (Breaking Changes that Would Cause Existing Functionality to NOT Work as Expected)

### To-Do or Other Concerns:

- (NONE)

### CODE REVIEW

**Comment by xiaoshaoyc** [comment]
I think you can use [code block](https://www.markdownguide.org/extended-syntax/#syntax-highlighting) for better formatting.

```json
{
	"id": "String",
	"Subject": "String",
	"sentTime": "String",
	"CC": "[String]",
	"To": "[String]",
	"From": "String",
	"Context": "String",
	"linkForAttaches": "[String]",
}
```

**Comment by xiaoshaoyc** [comment]
https://stackoverflow.com/a/44240048/8493359

**Review by wangz44 — APPROVED** [review]
nice

**Review by wangz44 — DISMISSED** [review]
nice

**Review by xiaokeai55 — APPROVED** [review]
good

**Review by XiaoyuYang18 — APPROVED** [review]
good

**Review by qit2 — APPROVED** [review]
Looks good

**Review by xiaoshaoyc — APPROVED** [review]

**Pull request merged**
