### PR TITLE
FEAT: Add `Messenger`, Create test for `SendEmailServiceImplTest`

### PR DESCRIPTION
**Pull request by xiaoshaoyc**
### Description of Changes:

Sync recent work with our main codebase.
- add `Messenger`, which handles the sending and retrieving of emails.
- add test case for `SendEmailServiceImplTest`.

### Type of Changes:

- [ ] Documentation (Add Documentation to Existing Code)
- [ ] Bug Fix (Non-Breaking Changes Which Fixes an Issue)
- [x] New Feature (Non-Breaking Changes Which Adds Functionality)
- [ ] Improvement (Non-Breaking Changes Which Improve the Structures, Performance, etc...)
- [ ] **Breaking Change** (Breaking Changes that Would Cause Existing Functionality to NOT Work as Expected)

### To-Do or Other Concerns:

- TODO: Automatic email testing via [testmail](https://testmail.app/)

### CODE REVIEW

**Review by wangz44 — DISMISSED** [review]

**Review by Viyerelu23333 — COMMENTED** [review]
Do you want to refactor the interface [`Messager`](https://github.com/RCOS-EasyContact/EasyContact/blob/93cb20842213f374fd9dd0609473d97d1dbda1c0/EasyContact.app/server/src/main/java/app/easycontact/messenger/Messager.java) to `Messenger`?

**Comment by xiaoshaoyc** [comment]
Fixed. Thank you.

> Do you want to refactor the interface [`Messager`](https://github.com/RCOS-EasyContact/EasyContact/blob/93cb20842213f374fd9dd0609473d97d1dbda1c0/EasyContact.app/server/src/main/java/app/easycontact/messenger/Messager.java) to `Messenger`?

**Review by Rexezuge — APPROVED** [review]
LGTM!

**Review by ZHIHANCHEN03 — APPROVED** [review]
Great improvement

**Pull request merged**
